# Generated by Django 3.0.8 on 2020-07-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(default='')),
                ('deliverfee', models.IntegerField()),
                ('orderfee', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=30)),
                ('adder', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(choices=[('UN', 'Unpublished'), ('PB', 'Published')], default='UN', max_length=2)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.Driver')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Store')),
            ],
        ),
    ]
