# Generated by Django 3.0.8 on 2020-07-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('SH', 'Shipped'), ('PB', 'Delivered')], default='PN', max_length=2),
        ),
    ]
