# Generated by Django 3.0.8 on 2020-07-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20200722_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliverfee',
            field=models.IntegerField(default=0),
        ),
    ]
