# Generated by Django 3.0.8 on 2020-07-24 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20200722_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NE', 'New'), ('PN', 'Pending'), ('SH', 'Shipped'), ('PB', 'Delivered'), ('CA', 'Cancelled')], default='NE', max_length=2),
        ),
    ]
