# Generated by Django 3.0.8 on 2020-07-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20200724_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customername',
            field=models.CharField(default='', max_length=300),
        ),
    ]
