# Generated by Django 3.0.8 on 2020-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_order_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adder',
            field=models.CharField(default='', max_length=1000, verbose_name='عنوان العميل '),
        ),
        migrations.AlterField(
            model_name='order',
            name='customername',
            field=models.CharField(default='', max_length=300, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='desc',
            field=models.TextField(default='', verbose_name='وصف الطلبية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderfee',
            field=models.IntegerField(default=0, help_text='اتركه فارغ لو كانت الطلبية مدفوعة', verbose_name='سعر الطلبية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='رقم جوال العميل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NE', 'جديدة لم يعين سائق'), ('PN', 'في انتظار وصول السائق للمتجر'), ('SH', 'تم الشحن للتسليم'), ('PB', 'استلمها العميل'), ('CA', 'ملغية')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='store',
            name='adder',
            field=models.CharField(default='', max_length=1000, verbose_name='عنوان العميل '),
        ),
    ]
