# Generated by Django 3.0.8 on 2020-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20200727_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='رقم الجوال '),
        ),
    ]
