# Generated by Django 3.0.8 on 2020-07-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20200727_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلبية', 'verbose_name_plural': 'طلبيات'},
        ),
    ]
