# Generated by Django 3.0.8 on 2020-07-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20200727_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='stores_logos/', verbose_name='شعار المتجر '),
        ),
    ]
