# Generated by Django 3.0.8 on 2020-07-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='شعار المتجر '),
        ),
    ]
