# Generated by Django 3.0.8 on 2020-07-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_auto_20200728_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(upload_to='stores_logos/', verbose_name='شعار المتجر '),
        ),
    ]
