# Generated by Django 3.0.8 on 2020-08-16 11:38

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_remove_store_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'سائق', 'verbose_name_plural': 'سائقين'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'متجر', 'verbose_name_plural': 'متاجر'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NE', 'جديدة لم يعين سائق'), ('PN', 'في انتظار وصول السائق للمتجر'), ('SH', 'تم الشحن للتسليم'), ('DE', 'استلمها العميل'), ('CA', 'ملغية')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='store',
            name='adder',
            field=models.CharField(default='', max_length=1000, verbose_name='عنوان المتجر '),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=500, verbose_name='اسم المتجر '),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'اسم المستخدم موجود بالفعل'}, help_text='يتطلب 150 حرف أو أقل .يمكن أن يحتوي أحرف أو ارقام أو @/./+/-/_ فقط.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='اسم المستخدم'),
        ),
    ]
