# Generated by Django 3.0.8 on 2020-08-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_auto_20200816_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliverfee',
            field=models.IntegerField(default=0, verbose_name='مصاريف الشحن'),
        ),
    ]
