# Generated by Django 3.0.8 on 2020-08-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_auto_20200816_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلب', 'verbose_name_plural': 'طلبات'},
        ),
        migrations.AddField(
            model_name='order',
            name='driverfee',
            field=models.IntegerField(default=20, verbose_name='حساب السائق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='desc',
            field=models.TextField(default='', verbose_name='وصف الطلب'),
        ),
    ]
